### ISSUE TITLE
Please add support for Version 3.x

### ISSUE THREAD

**Issue by kyotocanuck** [akiko-pusu/redmine_banner#106]
As stated, this banner plugin is simple by design. Please consider to allow support for version 3.x series of redmine. I am still on version 3.4 for the time being and would love to use this banner.

ダウンロードしてRedmine3.xに使えませんでした。このプラグイン情報を読んだら結構シンプルなんだから、もしちょっと古Redmineに使うのが凄く嬉しいです。

よろしくお願い致します。

**Comment by akiko-pusu** [comment]
@kyotocanuck 
Have you read README.md?

As I wrote, please try **v0.1.2** or **v0.1.x-support-Redmine3** branch in case using Redmine3.x.
You can download v0.1.2 from here:
- https://github.com/akiko-pusu/redmine_banner/releases/tag/0.1.2

See also: https://github.com/akiko-pusu/redmine_banner#020

**Comment by kyotocanuck** [comment]
Sorry I had only skimmed the installation information. Thank you for informing. As that is the case let’s close this issue as resolved. Thank you for your comment.

**Comment by akiko-pusu** [comment]
@kyotocanuck 
Personally I think this plugin is useful for administrators, so I’d like to support both Redmine3.x and Redmine4.x. 
But keeping compatibility to support both version of Redmine in one source is a little difficult for me, so that I’m sorry I could only sepalate the branch to support Redmine3.x.
If there any critical bug happens, I’m going to fix it against master branch and v0.1.x or v0.1.x-support-Redmine3 branch.

Thanks again for your using my plugin!
